// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3aa3MFylKXSWk9QyAdpgR2lPm5ZLlBmw',
    appId: '1:993319756555:web:94d26740efc1c960acb80e',
    messagingSenderId: '993319756555',
    projectId: 'glu-trotter-922e7',
    authDomain: 'glu-trotter-922e7.firebaseapp.com',
    storageBucket: 'glu-trotter-922e7.firebasestorage.app',
    measurementId: 'G-VSBYKG9Z9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACqifDzQDi42ig_JgeWdTBvXT_htrwJfY',
    appId: '1:993319756555:android:30c1fb7c6c3c70faacb80e',
    messagingSenderId: '993319756555',
    projectId: 'glu-trotter-922e7',
    storageBucket: 'glu-trotter-922e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgjR_gi1gs8vIFa9gJUfovbCyp6X8Hwq0',
    appId: '1:993319756555:ios:02e876c1442cd77facb80e',
    messagingSenderId: '993319756555',
    projectId: 'glu-trotter-922e7',
    storageBucket: 'glu-trotter-922e7.firebasestorage.app',
    iosClientId: '993319756555-d2kv2d7qgj2gnj9nfku20mve4ltirrra.apps.googleusercontent.com',
    iosBundleId: 'com.example.gluTrotter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3aa3MFylKXSWk9QyAdpgR2lPm5ZLlBmw',
    appId: '1:993319756555:web:7ce8e13d91da629cacb80e',
    messagingSenderId: '993319756555',
    projectId: 'glu-trotter-922e7',
    authDomain: 'glu-trotter-922e7.firebaseapp.com',
    storageBucket: 'glu-trotter-922e7.firebasestorage.app',
    measurementId: 'G-YH54WL71PT',
  );

}